[package]
name = "metrics-sqlite"
version = "0.1.0"
authors = ["Jeremy Knope <jeremy@astropad.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = ["sqlite"] }
diesel_migrations = "1.4.0"
# this seems to let us force bundled sqlite in disel
libsqlite3-sys = { version = "0.18.0", features = ["bundled"] }
metrics-core = { version = "^0.5" }
metrics-util = { version = "^0.3" }
hdrhistogram = { version = "^6.3", default-features = false }
thiserror = "1.0.20"

[dev-dependencies]
metrics-runtime = { version = "0.13.1", default-features = false }
metrics = "0.12.1"
