[package]
name = "metrics-sqlite"
version = "0.5.1"
authors = ["Jeremy Knope <jeremy@astropad.com>"]
description = "Library for providing SQLite backend for metrics"
keywords = ["metrics", "sqlite"]
categories = ["development-tools::debugging"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/metrics-sqlite"
repository = "https://github.com/AstroHQ/metrics-sqlite/"

[dependencies]
diesel = { version = "2.3", features = ["sqlite"] }
diesel_migrations = "2.3"
# this seems to let us force bundled sqlite in diesel
libsqlite3-sys = { version = "0.35.0", features = ["bundled"] }
metrics = "0.24"
thiserror = "2.0"
tracing = "0.1"
csv = { version = "1.1.6", optional = true }
serde = { version = "1.0", optional = true }
tokio = { version = "1.20", features = ["sync"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
tempfile = "3"

[features]
default = []
log_dropped_metrics = []
export_csv = ["csv", "serde/derive"]
import_csv = ["csv", "serde/derive"]

[[example]]
name = "export_csv"
required-features = ["export_csv"]

[[example]]
name = "import_csv"
required-features = ["import_csv"]
